### ISSUE TITLE
Consolidate the Link Wizard into a Single Window

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#112]
The wizard is causing too many issues.  I think that it is unnecessary and that it can be removed entirely.  Consolidate the link wizard into a single window.  This will also address [#111].

**Comment by Castronova** [comment]
Too much space about the link name box

**Comment by Castronova** [comment]
Spatial and Temporal interpolation labels should be right justified.

**Comment by marioharper182** [comment]
Should have fixed a couple of smaller styling issues, mac now is a little too much in the bottom (free space).

**Comment by Castronova** [comment]
How can we get rid of this extra space?
