### ISSUE TITLE
Drag and Drop models - unexpected behavior

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#125]
Models can be dragged and dropped from the toolbox onto the desktop.  We need to verify the drop target before performing doDrop.

**Comment by marioharper182** [comment]
The drag drop will still be able to drag off of the application (ie: onto the desktop) but this will be hard to stop unless dragging is removed entirely.

**Comment by Castronova** [comment]
We can't have things dragging off the application.  There must be a way to address this by checking the drop target before performing the drop operations.

**Comment by Castronova** [comment]
Any news on how to fix this?

**Comment by farrieta9** [comment]
Mario and I are thinking about removing this feature.

**Comment by marioharper182** [comment]
Note that there is still an issue with this on some platforms. Windows and linux seems to be having similar issues with the drag and does not respond nicely to the onEnter event handler.
The drag cursor needs some rework to match the application theme.

**Comment by Castronova** [comment]
duplicate of #202
