### ISSUE TITLE
Fix Context Menu Save-Load

### ISSUE THREAD

**Issue by marioharper182** [Castronova/EMIT#127]
The save and load context menu items on the Canvas are not responding.

**Comment by Castronova** [comment]
@marioharper182 Can you please test this on your mac

**Comment by Castronova** [comment]
@marioharper182 @farrieta9 Saving simulation doesn't seem to work.

**Comment by farrieta9** [comment]
When saving simulations from TimeSeries it will not work, otherwise it should.

**Comment by Castronova** [comment]
related to #200
