### ISSUE TITLE
Time Series needs unique names

### ISSUE THREAD

**Issue by marioharper182** [Castronova/EMIT#129]
When adding two models of the same type (ie: Rainfall) they need to be differentiated somehow (id, date, time, ect.. )

**Comment by farrieta9** [comment]
I've been tackling the issue about giving models different names when loading them.  I also had Jacob help me to figure out an idea.  After debugging it, Jacob said that this is a design error, and probably best to fix this so there are not bugs later in the future. 

I made an attempt at fixing this and pushed the commit.  I made it in such a way that if we wanted to use a different way to tell the difference we can.

**Comment by Castronova** [comment]
@farrieta9 Can you make this look nicer.
for example:

```
Variable Name
   ID = 56
```
