### ISSUE TITLE
Data Series does not plot

### ISSUE THREAD

**Issue by marioharper182** [Castronova/EMIT#132]
Any database object will not plot

**Comment by marioharper182** [comment]
On right click context for the database elements, the plot does not come up and the application freezes.

**Comment by Castronova** [comment]
This is because of a recent commit that I made to standardize spatial 
plotting.  To fix this, the database plotting needs to be refactored.

> Mario Harper <mailto:notifications@github.com>
> May 13, 2015 at 10:54 AM
>
> On right click context for the database elements, the plot does not 
> come up and the application freezes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Castronova/EMIT/issues/132#issuecomment-101745504>.
>
> Mario Harper <mailto:notifications@github.com>
> May 8, 2015 at 10:40 AM
>
> Any database object will not plot
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Castronova/EMIT/issues/132>.
>

-- 
Anthony Castronova
Research Assistant Professor
Utah Water Research Laboratory
Utah State University

**Comment by farrieta9** [comment]
When loading a simulations and trying to plot it the database['session'] is missing.

**Comment by Castronova** [comment]
**Timeseries** plotting has been fixed, but **Simulation** plotting still does not work.

**Comment by Castronova** [comment]
This should be fixed now.

**Comment by Castronova** [comment]
@marioharper182  please test this for me and close it if the issue is addressed

**Comment by Castronova** [comment]
Not working: `SetColumnWidth(): invalid column index`
