### ISSUE TITLE
Add button to link grid view

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#134]
Add a button to the description cell in the link dialog box that will open a new frame that displays the full text.  This will fix the issue of overflowing text in the grid view.

![screen shot 2015-05-08 at 2 38 06 pm](https://cloud.githubusercontent.com/assets/4822372/7545061/dded5f82-f58f-11e4-812c-33fbdb2b4d67.png)

**Comment by marioharper182** [comment]
I am thinking that we can use something like wx.EVT_GRID_LEFT_MOUSE instead of a button to open up a small textbox that has the full text.

**Comment by Castronova** [comment]
@marioharper182 This doesn't seem to work on OSX

**Comment by Castronova** [comment]
@marioharper182 should this be a **tool tip** instead?

**Comment by farrieta9** [comment]
We tested it on Mario's Mac and it worked.

**Comment by Castronova** [comment]
Please double check because this still isn't working on my computer.

farrieta9 wrote:

**Comment by marioharper182** [comment]
This feature is working on my mac but requires the user to click into the cell before the tool-tip is active.
