### ISSUE TITLE
Timeseries and Simulation data views need to fill all whitespace

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#136]
The data grid view elements that are used to display **timeseries** and **simulation** data do not extend to the window size which causes whitespace to be shown.  This look bad and needs to be fixed.

![screen shot 2015-05-08 at 3 05 28 pm](https://cloud.githubusercontent.com/assets/4822372/7545622/b66cebd6-f593-11e4-9a09-5c5b4174ba13.png)

**Comment by Castronova** [comment]
All columns should have a minimum width, but also expand to fit their contents.  This is evident when looking at simulation data.

**Comment by farrieta9** [comment]
Made the column a set width

**Comment by farrieta9** [comment]
I have to change the place where setColumnWidth is called because where it was before was giving an error when trying to plot from the database.
