### ISSUE TITLE
Application Freezes when Configuration fails to load

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#138]
When a configuration fails to load, errors cause the application to freeze/crash.  Need to add exception handling to prevent this from happening.

**Comment by farrieta9** [comment]
I added this to a commit also.

Application no longer freezes when configuration fails to load.   What it does instead is pop a message saying it failed to load. A try/except was added in logicCanvas.py in addModel method. This prevents errors for '.sim' files. Another try/except was added in engineManager.py in the worker method. This helped with any other freezes that could happen when loading '.mdl' or '.sim'.
