### ISSUE TITLE
Configuration Icons

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#139]
Need a unique icon for model configurations.

**Comment by marioharper182** [comment]
Done, added a molecule  icon for .sim files.

**Comment by Castronova** [comment]
Am I the only one that thinks this icon looks like an **X** ?  Maybe we should keep looking.

Also, lets try to keep the coloring theme consistent.

**Comment by farrieta9** [comment]
The icon has been changed to a blue ball.
