### ISSUE TITLE
Database 'session' missing when ploting

### ISSUE THREAD

**Issue by farrieta9** [Castronova/EMIT#144]
When loading a simulations and trying to plot it the database['session'] is missing.  

Traceback (most recent call last):
  File "/EMIT/gui/views/viewContext.py", line 360, in OnPlot
    x,y, resobj = self.getData(resultID)
  File "/EMIT/gui/views/viewContext.py", line 323, in getData
    session = self.parent.getDbSession()
  **File "/EMIT/gui/controller/logicDatabase.py", line 75, in getDbSession**
    **return db['session']**
KeyError: 'session'

**Comment by Castronova** [comment]
Mario, please test this and close.
