### ISSUE TITLE
Recolor the model components

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#150]
The colors for the time-step and data model components are terrible.  Choose colors that look nice.

**Comment by marioharper182** [comment]
We have created (in photoshop so there is no licensing issues) twelve shape objects that we can use if we need objects. They are in the images/resources file.

**Comment by marioharper182** [comment]
This looks best on Mac so far but Windows looks alright. Win8 and Win10 looks better then Win7. Manjaro and Ubuntu also looks fine.

**Comment by marioharper182** [comment]
Mac version is Yosemite
