### ISSUE TITLE
Can't remove duplicate database items of the same name

### ISSUE THREAD

**Issue by marioharper182** [Castronova/EMIT#152]
When a database object gets loaded, it cannot be cleared through the right-click delete context. No clue why. Also some of them delete but the text does not clear.

**Comment by mgallagher** [comment]
Looks like only the single most recently added time series box can be removed.

**Comment by mgallagher** [comment]
If you add a "cumulative precipitation" and a "rainfall" object, both can be removed just fine. However, if you add TWO of the same type, only the most recently added object can be removed. This might be related to issue #129

**Comment by mgallagher** [comment]
Guessing that the issue is here: https://github.com/Castronova/EMIT/blob/milestone-0.1.1/coordinator/engine.py#L341-381

**Comment by mgallagher** [comment]
Just testing
