### ISSUE TITLE
Windows - Get it to actually run

### ISSUE THREAD

**Issue by marioharper182** [Castronova/EMIT#162]
* Windows OS Issue
Items in the tree is not responding to being selected or dragged. 

I believe that either the binding (hopefully this is the issue) is what is not working right now. Or else it is a parent-child issue.

**Comment by ryanzj725** [comment]
0.1.5

It starts on windows, but the application freezes on startup.

It may be because of file path issues.

**Comment by Castronova** [comment]
@ryanzj725 I made some changes that I think fix this issue.  Please test.

**Comment by ryanzj725** [comment]
It is running, but still has some bugs
