### ISSUE TITLE
Clicking "Run" on context menu with model present crashes Linux

### ISSUE THREAD

**Issue by mgallagher** [Castronova/EMIT#163]

**Comment by mgallagher** [comment]
Might be good to add a safeguard. It's probably trying to perform calculations on nothing and gets stuck in an infinite loop.

**Comment by Castronova** [comment]
Run should be greyed out if there is no link

**Comment by mgallagher** [comment]
Run should probably be grayed out up in the top menu bar as well, but this will be more complicated.
