### ISSUE TITLE
System Crashes when trying to run simulations

### ISSUE THREAD

**Issue by farrieta9** [Castronova/EMIT#165]
For example, if you load multiplier and hit run the computer will crash.  You may need to turn off your computer!!!

**Comment by marioharper182** [comment]
Multiplier is a model that requires input arguments to run. We can have a general and robust test to see if all models requiring an input got one when the run is selected.

**Comment by farrieta9** [comment]
This has been resolved now that you can only run simulation when at least two models are on the float canvas.
