### ISSUE TITLE
Component fonts need consistency

### ISSUE THREAD

**Issue by mgallagher** [Castronova/EMIT#167]
Not sure if this is an issue with WX, but the fonts should ideally be set to whatever the system uses as its [sans-serif font](http://en.wikipedia.org/wiki/Sans-serif). Here's what I'm getting on OSX:
![screen shot 2015-06-03 at 11 47 32 am](https://cloud.githubusercontent.com/assets/1775621/7967322/9f2fb89c-09e6-11e5-8f9d-afc4d4322a40.png)

And Linux:
![image](https://cloud.githubusercontent.com/assets/1775621/7967535/d90636e4-09e7-11e5-92eb-169d02c7880b.png)

**Comment by marioharper182** [comment]
Yeah... I get the same too...
We thought about how to set the best fonts but the best way that we have found to do this is to just let wx use the system default fonts. (ie: depending on my theme in manjaro xfce or galaxy 2 changes the font size drastically)

**Comment by Castronova** [comment]
Maybe it would be best to embed the fonts that we want the application to use.

**Comment by marioharper182** [comment]
This might be a good idea, we do have a resources folder that everything is already pulling from on the gui end.
