### ISSUE TITLE
Component box drag-and-drop indicator

### ISSUE THREAD

**Issue by mgallagher** [Castronova/EMIT#168]
We might want to consider making slightly transparent versions of component boxes for dragging and dropping. Even more ideal would just be moving the entire component (like re-positioning an app icon on your phone), but I'm not sure if that's doable.

**Comment by marioharper182** [comment]
We can perhaps go with making a large cursor in the shape of a dotted box when onDrag is called. This could potentially solve this issue.

**Comment by Castronova** [comment]
@marioharper182  see if you can restore the dashed box, or replace it with the actual model object.

**Comment by mgallagher** [comment]
I've been taking a look at this today. Mario tells me this is handled in the OnMove function in logicCanvas.py, and I've been trying to figure out how to use the actual model object. So far efforts have been unsuccessful but I'll pick this up again tomorrow.

**Comment by mgallagher** [comment]
Drag and drop now working. Main issue now is when a link is present, this lowers FPS in the canvas drastically.

**Comment by mgallagher** [comment]
Drag and dropping has been working in conjunction with the old link / arrow style. Closed!
