### ISSUE TITLE
print statements should appear on the gui console not pycharm

### ISSUE THREAD

**Issue by farrieta9** [Castronova/EMIT#173]

**Comment by farrieta9** [comment]
The warnings and connections to the database statements should appear on the gui console but for some reason it is appearing on the pycharm console.

**Comment by Castronova** [comment]
With the new implementation, logging statements should appear in both places.

Need to refactor all of the print statements to one of the following:
* **INFO** - most of the output for the console window 
* **DEBUG** - debug specific info (temporary)
* **WARNING** - non-critical errors
* **ERROR** - errors
* **CRITICAL** - system crashes
