### ISSUE TITLE
Simultions tab not working

### ISSUE THREAD

**Issue by farrieta9** [Castronova/EMIT#183]
Sometimes in the simulations tab in the gui console does not work.

**Comment by Castronova** [comment]
Try to replicate on your mac,

**Comment by mgallagher** [comment]
This works fine on my Mac. Not sure what the issue is here :(

**Comment by farrieta9** [comment]
Ok, this issue is strange.  After booting up to manjaro i had this problem.  I tried debugging and noticed that it never enters the method where it is supposed to load the information.  So what I tried was going back a few commits until i found a place where it was working.   Once i got to May 28, 2015 it worked.  Sweet, so i went up to find the exact commit where it broke.  Turns out that if i commit back to the update it does work.  And now it continues to work.  Only thing is when i am in debug mode it does not work, but it will otherwise.
