### ISSUE TITLE
Unpredictable crashing when adding models

### ISSUE THREAD

**Issue by mgallagher** [Castronova/EMIT#198]
I'm unable to reproduce this, but about 10% of the time when adding a model to the canvas, the application breaks and no longer responds to input. This requires the app to be force-closed. Sometimes uncommenting [this thread instruction](https://github.com/Castronova/EMIT/blob/milestone-0.1.2/coordinator/engineAccessors.py#L21) on engineAccessors.py seems to help.

**Comment by farrieta9** [comment]
related to issue #199

**Comment by Castronova** [comment]
Lets hope that adding exception logging messages will help us figure this out.

**Comment by farrieta9** [comment]
The commits on Aug 13 fixed this, there should be no threading issues when loading models.
