### ISSUE TITLE
Plot Simulations Fails

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#229]
I get the following error when attempting to plot simulation data:

TypeError: Invalid argument(s) 'pool_timeout','max_overflow','pool_size' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by farrieta9** [comment]
This also happens when adding the model.  I will check it out.
