### ISSUE TITLE
Clean all plots

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#231]
Timeseries and spatial plots have been hacked together.  We need to fix these up and also move away from vanilla matplotlib.  We should look at:

Seaborn
Bokeh
Chaco
see: https://wiki.python.org/moin/NumericAndScientific/Plotting

**Comment by ryanzj725** [comment]
I will start working on this.

**Comment by ryanzj725** [comment]
Added some functionally to this, the plots are cleaned up and, to me, are easier on the eyes.
