### ISSUE TITLE
Add Connection Styling and Tests

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#283]
The Add connection dialog needs restyling.

* window title is `Sample Dialog`
* help button does nothing.
* need to verify that this still works (i.e. unit tests)

**Comment by Castronova** [comment]
Engine should support: PostrgeSQL, MySQL, SQLite.

Also need somewhere designate that this feature only supports ODM2 schemas.

**Comment by Castronova** [comment]
Restyle this and put into MVC

**Comment by Castronova** [comment]
* add tab navigation
* add more descriptive error message

**Comment by ryanzj725** [comment]
The only testing  ready is that the labels and text boxes get disabled when you change the engine type
