### ISSUE TITLE
NetCDF Subset View

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#288]
After the user chooses to add a netcdf dataset to the Canvas, we need to open a new window that allows them to subset the data.  This is necessary to retrieve info about specific variables and also so that the entire file is not downloaded if it is not required.

Mock up the view for this functionality

**Comment by Castronova** [comment]
Missing an add to canvas button

**Comment by ryanzj725** [comment]
Its been added

**Comment by farrieta9** [comment]
* Clean up space at the bottom of the netcdffile file info
* more space down the middle on the lower panel
* Make drop down all the same size.
