### ISSUE TITLE
Link Fails with Multiple connections

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#291]
The link dialog fails when checking for bidirectional link.  To replicate;

1. Add three models to canvas
2. Establish a link between models 1 and 2
3. Attempt to add a second link between models 2 and 3

**Comment by Castronova** [comment]
I added a quick fix for this issue.  Can you please verify that it still works as expected.

**Comment by farrieta9** [comment]
see also #300

**Comment by farrieta9** [comment]
I just checked it out.  It worked.  I tried to reproduce it using the steps you gave as well as other possible combinations and it always worked, swapping also worked.
