### ISSUE TITLE
NetCDF Viewer Cleanup

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#292]
* **Download** and **Add to Canvas** buttons should be deactivated if a netcdf file is not selected in the table above.

* add spacing between the url box and **Get** button

* Change **Get** to **Get Files**

* Change title from **Netcdf Viewer** to **THREDDS File Browser** 

* Fix the data to match the column headers.  Also, **URL** should be the last column

**Comment by Castronova** [comment]
* NetCDF viewer should disappear when **Add to Canvas** is selected.

**Comment by farrieta9** [comment]
*  Change addToCanvas to Open
* Keep the window on top

**Comment by Castronova** [comment]
* Netcdf view appears below the thredds browser window.
*Change title to the name of the file that was opened:  for example "NetCDF Viewer: prcp.nc"
