### ISSUE TITLE
WOF Viewer Cleanup

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#294]
* Preview, Export, and Add to Canvas buttons should be disabled if variable is not selected.

**Comment by Castronova** [comment]
* we need some method of cancelling a WOF query.  If a large query is made, the entire GUI locks up until it is finished.

**Comment by ryanzj725** [comment]
everything but the Wof query cancelling is done.

**Comment by ryanzj725** [comment]
Left to do:
* Disable export/add to canvas for more then one selected.
* WOF Query cancelling.

**Comment by Castronova** [comment]
* disable datetime pickers for ODM2 timeseries.
