### ISSUE TITLE
Bidirectional Link ReDesign

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#300]
The bidirectional link does not work as expected.  We need to rework our current implementation.

**Comment by farrieta9** [comment]
Bidirectional links work again.  Also made it so when you click on different links the input and output labels that display above the data change and show the respective model.

**Comment by Castronova** [comment]
Link `swap` is always disabled.  This button should allow us to swap the direction of the link and therefore allowing us to specify bidirectional data transfer.

**Comment by farrieta9** [comment]
The swap activates when a link is set to go both directions.  Have you tried setting the link arrow to go both directions?

**Comment by farrieta9** [comment]
A question mark should appear when a link is drawn between two models.  Clicking the link will bring up the link ctrl.  After adding a link object the arrow should be drawn depending on the direction of the link.  So 3 cases.  
1. if no link is added show the question mark. 
2. if link goes one way show arrow going one way
3 if there are links going both ways show a two way arrow.
