### ISSUE TITLE
Clean Plot Geometry View

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#313]
Need to improve the view for the geometry plotting (link dialog view).  

1. Replace color gradients with solid colors
2. Disable window resizing
3. Replace the **id** in the window title with "Link"

**Comment by farrieta9** [comment]
For the color gradients did you mean to make them darker? It seems like the gradient is all the same.

**Comment by Castronova** [comment]
The problem right now is that some of the features are too light, as you've mentioned.  However, we may just need to rethink our coloring method altogether.  We can choose color gradients that ensure all features are clearly visible, or maybe just use a single color to represent all features.  I'm going to leave this up to you to explore :)

**Comment by Castronova** [comment]
@farrieta9 Plotting is still using gradients (test against TOPMODEL).  We should only use solid colors, or gradients that will not result in very light (almost white) color

**Comment by Castronova** [comment]
@farrieta9 We need to clean up more items:
1. Change the title of the view (Geometry Viewer?)
2. display stats about the geometry types (bottom panel)
3. plotting one geometry displays gridlines, but gridlines disappear when both are selected
4. Need to think of a better way to display the input and output exchange items (above the plot) as well as the checkboxes below the plot.

**Comment by farrieta9** [comment]
This issue is almost done.  The only that is left is populating the grid with the correct data, and fixing the get_exchange_item_by_id in the engine.  For top model and weather reader the method returns None.
