### ISSUE TITLE
Simulation Plot Viewer WOF Style

### ISSUE THREAD

**Issue by ryanzj725** [Castronova/EMIT#317]
Move the simulation plot viewer to the WOF style

**Comment by farrieta9** [comment]
* implement plotting
* change the title "results for simulation: " + name of simulation
* disable add to canvas and export work on later
* implement start and end date or disable them.
* Columns change to Variable, units, Begin and end date or date created, and description

**Comment by farrieta9** [comment]
I believe there is inconsistency on the dates with simulations.  The dates differ from what it says in the emit odm2 under simulation start. this differs from the simulationctrl for the variable begin dates.  And those two are different from what the actual variable date object says it is.
