### ISSUE TITLE
Add statistics to the plot viewing

### ISSUE THREAD

**Issue by farrieta9** [Castronova/EMIT#356]

**Comment by Castronova** [comment]
* Geometry Type
* Coordinate System
* Extent
* Number of elements

**Comment by farrieta9** [comment]
I'm not finding the methods to get this information from the engine

**Comment by Castronova** [comment]
`engineAccessors.getOutputExchangeItems` method should give you **Coordinate System** and the geometry (from which **Number of Elements** can be derived.  I can add **Geometry Type** and **Extent** to this function as well.  

For input exchange items, the `engineAccessors.getOutputExchangeItems` should be used.

**Comment by farrieta9** [comment]
This is what the engineAccessors.getIn/OutputExchangeItems returns:
keys -> ['description', 'geom', 'variable', 'type', 'id', 'unit', 'name']
value -> ['unknown', [{'wkb': '\x00\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x05@>\x00\x00\x00\x00\x00\x00@$\x00\x00\x00\x00\x00\x00@D\x00\x00\x00\x00\x00\x00@D\x00\x00\x00\x00\x00\x00@4\x00\x00\x00\x00\x00\x00@D\x00\x00\x00\x00\x00\x00@$\x00\x00\x00\x00\x00\x00@4\x00\x00\x00\x00\x00\x00@>\x00\x00\x00\x00\x00\x00@$\x00\x00\x00\x00\x00\x00', 'id': '005ec627d7c4c7579b03d0c0f9530f1e696f221482ddf848c42660ff'}], <stdlib.Variable object at 0x11f8da1d0>, 'INPUT', '1e8f173c828c49ed896e1ea7f7f6d40b', <stdlib.Unit object at 0x11f8e6310>, 'some_value']

Using the ogr.CreateGeometryFromWkb function i get a object of type OGRGeometryShadow

Using the OGRGeometryShadow object i am able to use methods like GetCoordinateDimension() which returns an integer and i can also use GetGeometryName() which returns a geometry shape like polygon.  

Am i doing this wrong? What should the data look like?

**Comment by Castronova** [comment]
I'm working on implementing this in the engine.

**Comment by Castronova** [comment]
This has been implement in the engine

**Comment by farrieta9** [comment]
I've updated the statistics.  Let me know what you think of it
