### ISSUE TITLE
Temporal and spatial interpolation have no effect

### ISSUE THREAD

**Issue by farrieta9** [Castronova/EMIT#376]
In the LinkCtrl, the temporal interpolation and spatial seem to have no effect.  Perhaps we should consider finish the implementation, or have a way to test it, or remove it.

**Comment by Castronova** [comment]
This may be causing simulations to fail too.

**Comment by Castronova** [comment]
@farrieta9 Can you please explain the error that you are getting?

**Comment by farrieta9** [comment]
There is no error, the interplotation have no effect.  In other words, the interplotation is not doing anything.  Whether you set them or not it does nothing.
