### ISSUE TITLE
Configuration load Arrow not initialized

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#391]
When a configuration (.sim) file is loaded an contains a link, the arrow still displays **?**.  This may be due to the arrow not initializing correctly.

**Comment by ryanzj725** [comment]
On loading if you click the link and then hit cancel the link disapears and you can't add another

**Comment by ryanzj725** [comment]
the more I have looked at this the more I think the above comment is related to this issue in general.

**Comment by farrieta9** [comment]
It loads two separte images when loading a bidirectional link.
