### ISSUE TITLE
View details fails for NetCDF components

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#415]
1. Add netcdf component 
2. Right click and view details.

```
Traceback (most recent call last):
  File "C:/Users/Tony Castronova/Documents/EMIT\gui\views\ContextView.py", line 95, in ShowModelDetails
    model_details.PopulateProperties(engine.getModelById(self.model_obj.ID), iei=iei, oei=oei)
  File "C:/Users/Tony Castronova/Documents/EMIT\gui\controller\ModelCtrl.py", line 98, in PopulateProperties
    self.PopulatePropertyGrid(oei[0])
  File "C:/Users/Tony Castronova/Documents/EMIT\gui\controller\ModelCtrl.py", line 106, in PopulatePropertyGrid
    self.PopulatePropertyGrid(value)
  File "C:/Users/Tony Castronova/Documents/EMIT\gui\controller\ModelCtrl.py", line 109, in PopulatePropertyGrid
    self.PopulatePropertyGrid(value)
  File "C:/Users/Tony Castronova/Documents/EMIT\gui\controller\ModelCtrl.py", line 104, in PopulatePropertyGrid
    for key, value in dictionary.iteritems():
AttributeError: 'str' object has no attribute 'iteritems'
```

**Comment by farrieta9** [comment]
Do you have a netcdf component we can use to test this? I do know have a netcdf component (I assume your doing loading it from the app menu bar -> Add NetCDF -> Find file).

**Comment by farrieta9** [comment]
After testing this, the issue that is most commonly received is:
"list.remove(x): x not in list".

**Comment by farrieta9** [comment]
I've continued to debug this issue.  The issues seems to be in EMIT/wrappers/netcdf.py. The first error is in line ~58. dt = datetime.timedelta(**tunit). Timedelta needs a float and not a numpy.array.  The next issue is in lines ~62-68. variables.remove(t/s/ydim). Those variables can be the same and there will only exist one instance of them but we're trying to remove it two or three times. The third issue was in line ~71 numpy.meshgrid(x, y). I get some funky error. I couldn't get passed that but these are notes on this issue.

**Comment by farrieta9** [comment]
My last couple of comments do not apply to this. They are referring to the THREADS browser. I do not have a NetCDF component so i am unable to test this.

**Comment by Castronova** [comment]
@farrieta9  This no longer fails, but the `params` key-value pairs need to be cleaned up.
