### ISSUE TITLE
Clicking link doesn't load the link

### ISSUE THREAD

**Issue by ryanzj725** [Castronova/EMIT#427]
On linux clicking the link doesn't pull up the link controller

**Comment by Castronova** [comment]
This seems to be working on my machine (OSX).  We need to test on Windows and Linux.

@farrieta9, can you test this on linux?

**Comment by farrieta9** [comment]
It works on Mac and Windows.  For linux if you resize the lower panel then you should be able to click on the link.  I came across this by accident.  This is what I do on Manjaro.  It could be because of the focus of the image.
