### ISSUE TITLE
Add labels to spatial plots

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#62]
Spatial Definition plots need labels:
1.) coordinate labels along **left** and **bottom** sides
2.) Title above plot defined by the input/output features
3.) input/output units.

![screen shot 2014-11-04 at 1 36 31 pm](https://cloud.githubusercontent.com/assets/4822372/4907498/580889a0-6462-11e4-989b-8f3b525a14b2.png)

**Comment by marioharper182** [comment]
This has been finished.
