### ISSUE TITLE
Ylabel appears on Xaxis for time-series plots

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#89]
The Ylabel is drawn below the Xaxis when I plot time series values.

![screen shot 2015-01-13 at 10 40 32 am](https://cloud.githubusercontent.com/assets/4822372/5725496/9d517870-9b10-11e4-86f9-5f247178c710.png)

**Comment by marioharper182** [comment]
@jmeline fixed it. But I was the one who dared him to.
